### ISSUE TITLE
Make upstream-branch optional

### ISSUE THREAD

**Issue by neojski** [mozilla/moz-git-tools#22]
I'm happy with running:

```
git-push-to-try -t -r fx-team..HEAD ~/hg-fx-team 'try_options'
```

It contains all the information to push it to try. Upstream-branch seems not necessary here.

**Comment by amccreight** [comment]
Sorry for not looking at this earlier.  push-to-hg uses the -d option, which means (well, not right now, but once I fix a recently introduced bug) that if you have a local branch named origin/master it will just use that as the upstream.  At least, I think that's what ggp is able to do in issue #36.  Maybe you don't have origin/master and that isn't why it is working?  We could add some kind of option for your default upstream or something.

I assume that it needs the upstream to decide what to set the hg repo to before applying your patches, or something like that, so I feel like we can't get away with it entirely.

**Comment by neojski** [comment]
I'm not entirely sure what's the status for this bug now. I wasn't working on gecko-dev recently and I learned mercurial so it's no longer an issue for me. Most likely you explained that this should be fixed by now. Thanks!

**Comment by amccreight** [comment]
Ok, thanks!  I guess I'll just close this and wait for other people to complain if it bothers them. :)
