### ISSUE TITLE
Clarify what is PATH_TO_HG_REPO?

### ISSUE THREAD

**Issue by juj** [mozilla/moz-git-tools#49]
I'm learning how to use these, and looking at doing a push to try server with git-push-to-trychooser. The main page readme.MD talks about `PATH_TO_HG_REPO`, however I don't quite understand what that refers to. Do I need to have mozilla-central Mercurial repository cloned locally and PATH_TO_HG_REPO should point to that, e.g. ~/mozilla-central/? (If so, why? is gecko-dev mirror not enough?) Or should PATH_TO_HG_REPO point perhaps to https://hg.mozilla.org/mozilla-central/ ?

**Comment by amccreight** [comment]
Yes, the documentation is not very clear. PATH_TO_HG_REPO is indeed supposed to be a local clone of whatever Mozilla repo you want to push to try against. The way push-to-try works is that it figures out which patches are in your git repo that are not in your hg repo, and uses hg qpush to add them all to the hg repo. Then it does a push to try from the hg repo.

If you'd prefer to push directly to hg from git (which is certainly less clunky), check out git-cinnabar: https://github.com/glandium/git-cinnabar
