### ISSUE TITLE
Tagged release does not include cached version of submodule

### ISSUE THREAD

**Issue by rwhogg** [mozilla/moz-git-tools#57]
The newly tagged release https://github.com/mozilla/moz-git-tools/releases/tag/v0.1 includes a .gitmodules file and an empty git-bz-moz folder.

It would be more helpful if it included a cached version of the submodule's contents.

Discovered while importing it into Homebrew stable (https://github.com/Homebrew/homebrew/pull/47129)

Thanks a bunch for your help!

**Comment by rwhogg** [comment]
As it turns out, fixing this requires no action on your end. Sorry!

**Comment by amccreight** [comment]
Ok, great, thanks for letting me know.
